language: go

git:
    submodules: false

go:
    - 1.13.7
    - tip

script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
    - nvm install node
    - npm install prettier -g
    - make check
